spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_study
#    url: jdbc:mysql://host.docker.internal:3306/login_study
    username: login_study_dev
    password: 12345678
server:
  port: 7777
logging:
  level:
    org:
      springframework:
        security: DEBUG